substitutions:
  name: apollo-r-pro-1-w-edf0f8
  friendly_name: kitchen-motion
packages:
  ApolloAutomation.R-PRO-1-W: github://ApolloAutomation/R_PRO-1/Integrations/ESPHome/R_PRO-1_W.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret kitchen_motion_api_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
