esphome:
  name: central-heating
  friendly_name: Central Heating

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret central_heating_api_encryption_key

ota:
  - platform: esphome
    password: !secret central_heating_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Central-Heating Fallback Hotspot"
    password: !secret central_heating_hot_spot_password

captive_portal:

# LED exposed as binary light
output:
  - platform: gpio
    pin: GPIO23
    id: output_led

light:
  - platform: binary
    id: light_led
    name: LED
    output: output_led

# Relays exposed as switches
switch:
  - platform: gpio
    pin: GPIO16
    id: relay_1
    name: Relay 1

  - platform: gpio
    pin: GPIO17
    id: relay_2
    name: Relay 2
